export const headerLinks = [
  // { label: "Sign In", url: "/sign-in" },
  // { label: "Forgot Password", url: "/forgot-password" },
];

export const propertyDetail = [
  {
    propertyInformation: {
      name: "Debune",
      locality: "Dwarka",
      city: "New Delhi",
      address: "Dwarka sector 67, New Delhi, 110089",
      postalCode: "110089",
      country: "India",
      status: "Completed",
      type: "Society",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis dui in enim ultricies congue. Vivamus vel orci metus. Aenean eu metus sed eros sodales ultrices. In vitae fringilla arcu, vel convallis tellus. Nulla iaculis, sapien.",
      amenities: {
        carParking: 1,
        windowsAC: 1,
        geyser: 2,
        bed: 4,
        gasStove: 1,
        internet: 1,
        sofa: 2,
        television: 1,
        kitchenAppliance: 4,
        servantRoom: 1,
        waterPurifier: 1,
        cookTop: 1,
        geyserAdd: 1,
      },
      quotation:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis dui in enim ultricies congue. Vivamus vel orci metus. Aenean eu metus sed eros sodales ultrices. In vitae fringilla arcu, vel convallis tellus. Nulla iaculis, sapien.",
      invoice:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis dui in enim ultricies congue. Vivamus vel orci metus. Aenean eu metus sed eros sodales ultrices. In vitae fringilla arcu, vel convallis tellus. Nulla iaculis, sapien.",
      creditNote:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis dui in enim ultricies congue. Vivamus vel orci metus. Aenean eu metus sed eros sodales ultrices. In vitae fringilla arcu, vel convallis tellus. Nulla iaculis, sapien.",
      images: ["image1.png", "image2.png"],
      propertyTour: "tour_video.mp4",
      documents: ["Property2doc.doc", "Tenantdoc.doc"],
    },
    companyInformation: {
      companyName: "Debune",
      companyAddress: "Dwarka sector 67, Delhi , 110089",
      countryCode: +91,
      phoneNumber: 9876765467,
      tAXName: "Lore Ipsum",
      tAXNumber: "ASTGAG7738129487380002",
    },
  },
];

export const ownerDummyData = [
  {
    "#": 1,
    "Owner Name": "John Doe",
    "Current Address": "123 Main St, Anytown",
    Property: "Apartment",
    Unit: "A-101",
    Status: "Active",
  },
  {
    "#": 2,
    "Owner Name": "Jane Smith",
    "Current Address": "456 Elm St, Another Town",
    Property: "House",
    Unit: "A-102",
    Status: "Inactive",
  },
  {
    "#": 3,
    "Owner Name": "Mike Johnson",
    "Current Address": "789 Oak St, Cityville",
    Property: "Office Building",
    Unit: "A-103",
    Status: "Active",
  },
  {
    "#": 4,
    "Owner Name": "Emily Brown",
    "Current Address": "321 Pine St, Townsville",
    Property: "Warehouse",
    Unit: "A-104",
    Status: "Inactive",
  },
  {
    "#": 5,
    "Owner Name": "David Wilson",
    "Current Address": "987 Cedar St, Metropolis",
    Property: "Condo",
    Unit: "A-105",
    Status: "Active",
  },
  {
    "#": 6,
    "Owner Name": "Sarah Miller",
    "Current Address": "654 Birch St, Megatown",
    Property: "Retail Store",
    Unit: "A-106",
    Status: "Inactive",
  },
  {
    "#": 7,
    "Owner Name": "Chris Taylor",
    "Current Address": "246 Maple St, Smalltown",
    Property: "Villa",
    Unit: "A-107",
    Status: "Active",
  },
  {
    "#": 8,
    "Owner Name": "Rachel Clark",
    "Current Address": "135 Walnut St, Bigcity",
    Property: "Factory",
    Unit: "A-108",
    Status: "Inactive",
  },
  {
    "#": 9,
    "Owner Name": "Mark Davis",
    "Current Address": "543 Cherry St, Metrotown",
    Property: "Apartment Complex",
    Unit: "A-109",
    Status: "Active",
  },
  {
    "#": 10,
    "Owner Name": "Lisa Martinez",
    "Current Address": "876 Spruce St, Hospitalville",
    Property: "Medical Clinic",
    Unit: "Suite 101",
    Status: "Inactive",
  },
  {
    "#": 11,
    "Owner Name": "Andrew Adams",
    "Current Address": "432 Fir St, Villageland",
    Property: "Warehouse",
    Unit: "Warehouse 3",
    Status: "Active",
  },
];

export const propertyData = [
  {
    id: 1,
    property: "Sunset Villa",
    type: "Residential",
    status: "Completed",
    city: "Los Angeles",
    state: "California",
    country: "USA",
    postalCode: "90001",
    address: "123 Sunset Blvd",
    locality: "Sunset District",
    description:
      "A luxurious villa with a stunning sunset view, equipped with modern amenities and spacious living areas.",
    totalBlock: 5,
    totalUnit: 50,
    totalVacantUnit: 5,
    underNotice: 2,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["sunset_villa1.png", "sunset_villa2.png"],
    propertyTour: "sunset_villa_tour.mp4",
    documents: ["SunsetVillaDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 2,
    property: "Ocean View",
    type: "Residential",
    status: "Under Construction",
    city: "Miami",
    state: "Florida",
    country: "USA",
    postalCode: "33101",
    address: "456 Ocean Drive",
    locality: "South Beach",
    description:
      "A premium residential complex offering breathtaking ocean views and contemporary design.",
    totalBlock: 5,
    totalUnit: 30,
    totalVacantUnit: 10,
    underNotice: 1,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["ocean_view1.png", "ocean_view2.png"],
    propertyTour: "ocean_view_tour.mp4",
    documents: ["OceanViewDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 3,
    property: "Palm Grove Apartments",
    type: "Residential",
    status: "Completed",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postalCode: "400001",
    address: "789 Palm Road",
    locality: "Palm Grove",
    description:
      "Spacious apartments in the heart of Mumbai with excellent amenities and vibrant surroundings.",
    totalBlock: 12,
    totalUnit: 120,
    totalVacantUnit: 15,
    underNotice: 5,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["palm_grove_apartments1.png", "palm_grove_apartments2.png"],
    propertyTour: "palm_grove_apartments_tour.mp4",
    documents: ["PalmGroveDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 4,
    property: "Royal Residency",
    type: "Residential",
    status: "Completed",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    postalCode: "110001",
    address: "321 Royal Lane",
    locality: "Rajouri Garden",
    description:
      "An upscale residential complex featuring elegant design and modern amenities.",
    totalBlock: 7,
    totalUnit: 80,
    totalVacantUnit: 10,
    underNotice: 3,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["royal_residency1.png", "royal_residency2.png"],
    propertyTour: "royal_residency_tour.mp4",
    documents: ["RoyalResidencyDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 5,
    property: "Green Meadows",
    type: "Residential",
    status: "Completed",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    postalCode: "560001",
    address: "654 Green Avenue",
    locality: "Green Meadows",
    description:
      "A sprawling residential complex with lush greenery and state-of-the-art facilities.",
    totalBlock: 4,
    totalUnit: 150,
    totalVacantUnit: 20,
    underNotice: 4,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["green_meadows1.png", "green_meadows2.png"],
    propertyTour: "green_meadows_tour.mp4",
    documents: ["GreenMeadowsDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 6,
    property: "Sunrise Towers",
    type: "Residential",
    status: "Completed",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    postalCode: "600001",
    address: "987 Sunrise Street",
    locality: "T. Nagar",
    description:
      "A modern residential tower offering excellent amenities and panoramic city views.",
    totalBlock: 5,
    totalUnit: 100,
    totalVacantUnit: 12,
    underNotice: 6,
    leaseStatus: "Active",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["sunrise_towers1.png", "sunrise_towers2.png"],
    propertyTour: "sunrise_towers_tour.mp4",
    documents: ["SunriseTowersDoc.doc", "TenantDoc.doc"],
  },
  {
    id: 7,
    property: "Golden Heights",
    type: "Residential",
    status: "Completed",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    postalCode: "500001",
    address: "741 Golden Drive",
    locality: "Banjara Hills",
    description:
      "Elegant residential units offering a blend of comfort and style in a prime location.",
    totalBlock: 5,
    totalUnit: 90,
    totalVacantUnit: 18,
    underNotice: 2,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["golden_heights1.png", "golden_heights2.png"],
    propertyTour: "golden_heights_tour.mp4",
    documents: ["GoldenHeightsDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 8,
    property: "Silver Sands",
    type: "Residential",
    status: "Completed",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    postalCode: "411001",
    address: "852 Silver Street",
    locality: "Kothrud",
    description:
      "Stylish residential complex with top-notch amenities and a serene environment.",
    totalBlock: 10,
    totalUnit: 70,
    totalVacantUnit: 8,
    underNotice: 1,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["silver_sands1.png", "silver_sands2.png"],
    propertyTour: "silver_sands_tour.mp4",
    documents: ["SilverSandsDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 9,
    property: "Crystal Palace",
    type: "Residential",
    status: "Completed",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    postalCode: "700001",
    address: "963 Crystal Lane",
    locality: "Salt Lake",
    description:
      "Spacious and elegant residential units with excellent facilities in a well-connected area.",
    totalBlock: 20,
    totalUnit: 110,
    totalVacantUnit: 14,
    underNotice: 3,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["crystal_palace1.png", "crystal_palace2.png"],
    propertyTour: "crystal_palace_tour.mp4",
    documents: ["CrystalPalaceDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 10,
    property: "Blue Lagoon",
    type: "Residential",
    status: "Completed",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    postalCode: "380001",
    address: "852 Blue Lagoon Road",
    locality: "Vastrapur",
    description:
      "Luxurious living with top-quality amenities and a beautiful setting near the lagoon.",
    totalBlock: 25,
    totalUnit: 95,
    totalVacantUnit: 11,
    underNotice: 2,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["blue_lagoon1.png", "blue_lagoon2.png"],
    propertyTour: "blue_lagoon_tour.mp4",
    documents: ["BlueLagoonDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 11,
    property: "Emerald Greens",
    type: "Residential",
    status: "Completed",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    postalCode: "302001",
    address: "741 Emerald Street",
    locality: "C-Scheme",
    description:
      "A beautiful residential area with green surroundings and modern facilities.",
    totalBlock: 45,
    totalUnit: 85,
    totalVacantUnit: 7,
    underNotice: 4,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["emerald_greens1.png", "emerald_greens2.png"],
    propertyTour: "emerald_greens_tour.mp4",
    documents: ["EmeraldGreensDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
  {
    id: 12,
    property: "The Horizon",
    type: "Residential",
    status: "Completed",
    city: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    postalCode: "226001",
    address: "369 Horizon Road",
    locality: "Gomti Nagar",
    description:
      "Elegant residential units with modern amenities and a great view of the city.",
    totalBlock: 50,
    totalUnit: 60,
    totalVacantUnit: 5,
    underNotice: 1,
    leaseStatus: "Inactive",
    amenities: {
      carParking: 1,
      windowsAC: 1,
      geyser: 2,
      bed: 4,
      gasStove: 1,
      internet: 1,
      sofa: 2,
      television: 1,
      kitchenAppliance: 4,
      servantRoom: 1,
      waterPurifier: 1,
      cookTop: 1,
      geyserAdd: 1,
    },
    images: ["the_horizon1.png", "the_horizon2.png"],
    propertyTour: "the_horizon_tour.mp4",
    documents: ["TheHorizonDoc.doc", "TenantDoc.doc"],
    company: {
      name: "DLF",
      address: "123, Avenue, Suite 330, Boston, MA",
      phoneNumber: "9876543210",
      tAXName: "N/A",
      tAXNumber: "4234234234",
    },
  },
];

export const countryOptions = [
  { label: "Afghanistan", code: "93", iso: "AF", type: "country" },
  { label: "Albania", code: "355", iso: "AL", type: "country" },
  { label: "Algeria", code: "213", iso: "DZ", type: "country" },
  { label: "American Samoa", code: "1-684", iso: "AS", type: "country" },
  { label: "Andorra", code: "376", iso: "AD", type: "country" },
  { label: "Angola", code: "244", iso: "AO", type: "country" },
  { label: "Anguilla", code: "1-264", iso: "AI", type: "country" },
  { label: "Antarctica", code: "672", iso: "AQ", type: "country" },
  { label: "Antigua and Barbuda", code: "1-268", iso: "AG", type: "country" },
  { label: "Argentina", code: "54", iso: "AR", type: "country" },
  { label: "Armenia", code: "374", iso: "AM", type: "country" },
  { label: "Aruba", code: "297", iso: "AW", type: "country" },
  { label: "Australia", code: "61", iso: "AU", type: "country" },
  { label: "Austria", code: "43", iso: "AT", type: "country" },
  { label: "Azerbaijan", code: "994", iso: "AZ", type: "country" },
  { label: "Bahamas", code: "1-242", iso: "BS", type: "country" },
  { label: "Bahrain", code: "973", iso: "BH", type: "country" },
  { label: "Bangladesh", code: "880", iso: "BD", type: "country" },
  { label: "Barbados", code: "1-246", iso: "BB", type: "country" },
  { label: "Belarus", code: "375", iso: "BY", type: "country" },
  { label: "Belgium", code: "32", iso: "BE", type: "country" },
  { label: "Belize", code: "501", iso: "BZ", type: "country" },
  { label: "Benin", code: "229", iso: "BJ", type: "country" },
  { label: "Bermuda", code: "1-441", iso: "BM", type: "country" },
  { label: "Bhutan", code: "975", iso: "BT", type: "country" },
  { label: "Bolivia", code: "591", iso: "BO", type: "country" },
  { label: "Bosnia and Herzegovina", code: "387", iso: "BA", type: "country" },
  { label: "Botswana", code: "267", iso: "BW", type: "country" },
  { label: "Brazil", code: "55", iso: "BR", type: "country" },
  {
    label: "British Indian Ocean Territory",
    code: "246",
    iso: "IO",
    type: "country",
  },
  {
    label: "British Virgin Islands",
    code: "1-284",
    iso: "VG",
    type: "country",
  },
  { label: "Brunei", code: "673", iso: "BN", type: "country" },
  { label: "Bulgaria", code: "359", iso: "BG", type: "country" },
  { label: "Burkina Faso", code: "226", iso: "BF", type: "country" },
  { label: "Burundi", code: "257", iso: "BI", type: "country" },
  { label: "Cambodia", code: "855", iso: "KH", type: "country" },
  { label: "Cameroon", code: "237", iso: "CM", type: "country" },
  { label: "Canada", code: "1", iso: "CA", type: "country" },
  { label: "Cape Verde", code: "238", iso: "CV", type: "country" },
  { label: "Cayman Islands", code: "1-345", iso: "KY", type: "country" },
  {
    label: "Central African Republic",
    code: "236",
    iso: "CF",
    type: "country",
  },
  { label: "Chad", code: "235", iso: "TD", type: "country" },
  { label: "Chile", code: "56", iso: "CL", type: "country" },
  { label: "China", code: "86", iso: "CN", type: "country" },
  { label: "Christmas Island", code: "61", iso: "CX", type: "country" },
  { label: "Cocos Islands", code: "61", iso: "CC", type: "country" },
  { label: "Colombia", code: "57", iso: "CO", type: "country" },
  { label: "Comoros", code: "269", iso: "KM", type: "country" },
  { label: "Cook Islands", code: "682", iso: "CK", type: "country" },
  { label: "Costa Rica", code: "506", iso: "CR", type: "country" },
  { label: "Croatia", code: "385", iso: "HR", type: "country" },
  { label: "Cuba", code: "53", iso: "CU", type: "country" },
  { label: "Curacao", code: "599", iso: "CW", type: "country" },
  { label: "Cyprus", code: "357", iso: "CY", type: "country" },
  { label: "Czech Republic", code: "420", iso: "CZ", type: "country" },
  {
    label: "Democratic Republic of the Congo",
    code: "243",
    iso: "CD",
    type: "country",
  },
  { label: "Denmark", code: "45", iso: "DK", type: "country" },
  { label: "Djibouti", code: "253", iso: "DJ", type: "country" },
  { label: "Dominica", code: "1-767", iso: "DM", type: "country" },
  {
    label: "Dominican Republic",
    code: "1-809, 1-829, 1-849",
    iso: "DO",
    type: "country",
  },
  { label: "East Timor", code: "670", iso: "TL", type: "country" },
  { label: "Ecuador", code: "593", iso: "EC", type: "country" },
  { label: "Egypt", code: "20", iso: "EG", type: "country" },
  { label: "El Salvador", code: "503", iso: "SV", type: "country" },
  { label: "Equatorial Guinea", code: "240", iso: "GQ", type: "country" },
  { label: "Eritrea", code: "291", iso: "ER", type: "country" },
  { label: "Estonia", code: "372", iso: "EE", type: "country" },
  { label: "Ethiopia", code: "251", iso: "ET", type: "country" },
  { label: "Falkland Islands", code: "500", iso: "FK", type: "country" },
  { label: "Faroe Islands", code: "298", iso: "FO", type: "country" },
  { label: "Fiji", code: "679", iso: "FJ", type: "country" },
  { label: "Finland", code: "358", iso: "FI", type: "country" },
  { label: "France", code: "33", iso: "FR", type: "country" },
  { label: "French Polynesia", code: "689", iso: "PF", type: "country" },
  { label: "Gabon", code: "241", iso: "GA", type: "country" },
  { label: "Gambia", code: "220", iso: "GM", type: "country" },
  { label: "Georgia", code: "995", iso: "GE", type: "country" },
  { label: "Germany", code: "49", iso: "DE", type: "country" },
  { label: "Ghana", code: "233", iso: "GH", type: "country" },
  { label: "Gibraltar", code: "350", iso: "GI", type: "country" },
  { label: "Greece", code: "30", iso: "GR", type: "country" },
  { label: "Greenland", code: "299", iso: "GL", type: "country" },
  { label: "Grenada", code: "1-473", iso: "GD", type: "country" },
  { label: "Guam", code: "1-671", iso: "GU", type: "country" },
  { label: "Guatemala", code: "502", iso: "GT", type: "country" },
  { label: "Guernsey", code: "44-1481", iso: "GG", type: "country" },
  { label: "Guinea", code: "224", iso: "GN", type: "country" },
  { label: "Guinea-Bissau", code: "245", iso: "GW", type: "country" },
  { label: "Guyana", code: "592", iso: "GY", type: "country" },
  { label: "Haiti", code: "509", iso: "HT", type: "country" },
  { label: "Honduras", code: "504", iso: "HN", type: "country" },
  { label: "Hong Kong", code: "852", iso: "HK", type: "country" },
  { label: "Hungary", code: "36", iso: "HU", type: "country" },
  { label: "Iceland", code: "354", iso: "IS", type: "country" },
  { label: "India", code: "91", iso: "IN", type: "country" },
  { label: "Indonesia", code: "62", iso: "ID", type: "country" },
  { label: "Iran", code: "98", iso: "IR", type: "country" },
  { label: "Iraq", code: "964", iso: "IQ", type: "country" },
  { label: "Ireland", code: "353", iso: "IE", type: "country" },
  { label: "Isle of Man", code: "44-1624", iso: "IM", type: "country" },
  { label: "Israel", code: "972", iso: "IL", type: "country" },
  { label: "Italy", code: "39", iso: "IT", type: "country" },
  { label: "Ivory Coast", code: "225", iso: "CI", type: "country" },
  { label: "Jamaica", code: "1-876", iso: "JM", type: "country" },
  { label: "Japan", code: "81", iso: "JP", type: "country" },
  { label: "Jersey", code: "44-1534", iso: "JE", type: "country" },
  { label: "Jordan", code: "962", iso: "JO", type: "country" },
  { label: "Kazakhstan", code: "7", iso: "KZ", type: "country" },
  { label: "Kenya", code: "254", iso: "KE", type: "country" },
  { label: "Kiribati", code: "686", iso: "KI", type: "country" },
  { label: "Kosovo", code: "383", iso: "XK", type: "country" },
  { label: "Kuwait", code: "965", iso: "KW", type: "country" },
  { label: "Kyrgyzstan", code: "996", iso: "KG", type: "country" },
  { label: "Laos", code: "856", iso: "LA", type: "country" },
  { label: "Latvia", code: "371", iso: "LV", type: "country" },
  { label: "Lebanon", code: "961", iso: "LB", type: "country" },
  { label: "Lesotho", code: "266", iso: "LS", type: "country" },
  { label: "Liberia", code: "231", iso: "LR", type: "country" },
  { label: "Libya", code: "218", iso: "LY", type: "country" },
  { label: "Liechtenstein", code: "423", iso: "LI", type: "country" },
  { label: "Lithuania", code: "370", iso: "LT", type: "country" },
  { label: "Luxembourg", code: "352", iso: "LU", type: "country" },
  { label: "Macau", code: "853", iso: "MO", type: "country" },
  { label: "Macedonia", code: "389", iso: "MK", type: "country" },
  { label: "Madagascar", code: "261", iso: "MG", type: "country" },
  { label: "Malawi", code: "265", iso: "MW", type: "country" },
  { label: "Malaysia", code: "60", iso: "MY", type: "country" },
  { label: "Maldives", code: "960", iso: "MV", type: "country" },
  { label: "Mali", code: "223", iso: "ML", type: "country" },
  { label: "Malta", code: "356", iso: "MT", type: "country" },
  { label: "Marshall Islands", code: "692", iso: "MH", type: "country" },
  { label: "Mauritania", code: "222", iso: "MR", type: "country" },
  { label: "Mauritius", code: "230", iso: "MU", type: "country" },
  { label: "Mayotte", code: "262", iso: "YT", type: "country" },
  { label: "Mexico", code: "52", iso: "MX", type: "country" },
  { label: "Micronesia", code: "691", iso: "FM", type: "country" },
  { label: "Moldova", code: "373", iso: "MD", type: "country" },
  { label: "Monaco", code: "377", iso: "MC", type: "country" },
  { label: "Mongolia", code: "976", iso: "MN", type: "country" },
  { label: "Montenegro", code: "382", iso: "ME", type: "country" },
  { label: "Montserrat", code: "1-664", iso: "MS", type: "country" },
  { label: "Morocco", code: "212", iso: "MA", type: "country" },
  { label: "Mozambique", code: "258", iso: "MZ", type: "country" },
  { label: "Myanmar", code: "95", iso: "MM", type: "country" },
  { label: "Namibia", code: "264", iso: "NA", type: "country" },
  { label: "Nauru", code: "674", iso: "NR", type: "country" },
  { label: "Nepal", code: "977", iso: "NP", type: "country" },
  { label: "Netherlands", code: "31", iso: "NL", type: "country" },
  { label: "Netherlands Antilles", code: "599", iso: "AN", type: "country" },
  { label: "New Caledonia", code: "687", iso: "NC", type: "country" },
  { label: "New Zealand", code: "64", iso: "NZ", type: "country" },
  { label: "Nicaragua", code: "505", iso: "NI", type: "country" },
  { label: "Niger", code: "227", iso: "NE", type: "country" },
  { label: "Nigeria", code: "234", iso: "NG", type: "country" },
  { label: "Niue", code: "683", iso: "NU", type: "country" },
  { label: "North Korea", code: "850", iso: "KP", type: "country" },
  {
    label: "Northern Mariana Islands",
    code: "1-670",
    iso: "MP",
    type: "country",
  },
  { label: "Norway", code: "47", iso: "NO", type: "country" },
  { label: "Oman", code: "968", iso: "OM", type: "country" },
  { label: "Pakistan", code: "92", iso: "PK", type: "country" },
  { label: "Palau", code: "680", iso: "PW", type: "country" },
  { label: "Palestine", code: "970", iso: "PS", type: "country" },
  { label: "Panama", code: "507", iso: "PA", type: "country" },
  { label: "Papua New Guinea", code: "675", iso: "PG", type: "country" },
  { label: "Paraguay", code: "595", iso: "PY", type: "country" },
  { label: "Peru", code: "51", iso: "PE", type: "country" },
  { label: "Philippines", code: "63", iso: "PH", type: "country" },
  { label: "Pitcairn", code: "64", iso: "PN", type: "country" },
  { label: "Poland", code: "48", iso: "PL", type: "country" },
  { label: "Portugal", code: "351", iso: "PT", type: "country" },
  { label: "Puerto Rico", code: "1-787, 1-939", iso: "PR", type: "country" },
  { label: "Qatar", code: "974", iso: "QA", type: "country" },
  { label: "Republic of the Congo", code: "242", iso: "CG", type: "country" },
  { label: "Reunion", code: "262", iso: "RE", type: "country" },
  { label: "Romania", code: "40", iso: "RO", type: "country" },
  { label: "Russia", code: "7", iso: "RU", type: "country" },
  { label: "Rwanda", code: "250", iso: "RW", type: "country" },
  { label: "Saint Barthelemy", code: "590", iso: "BL", type: "country" },
  { label: "Saint Helena", code: "290", iso: "SH", type: "country" },
  { label: "Saint Kitts and Nevis", code: "1-869", iso: "KN", type: "country" },
  { label: "Saint Lucia", code: "1-758", iso: "LC", type: "country" },
  { label: "Saint Martin", code: "590", iso: "MF", type: "country" },
  {
    label: "Saint Pierre and Miquelon",
    code: "508",
    iso: "PM",
    type: "country",
  },
  {
    label: "Saint Vincent and the Grenadines",
    code: "1-784",
    iso: "VC",
    type: "country",
  },
  { label: "Samoa", code: "685", iso: "WS", type: "country" },
  { label: "San Marino", code: "378", iso: "SM", type: "country" },
  { label: "Sao Tome and Principe", code: "239", iso: "ST", type: "country" },
  { label: "Saudi Arabia", code: "966", iso: "SA", type: "country" },
  { label: "Senegal", code: "221", iso: "SN", type: "country" },
  { label: "Serbia", code: "381", iso: "RS", type: "country" },
  { label: "Seychelles", code: "248", iso: "SC", type: "country" },
  { label: "Sierra Leone", code: "232", iso: "SL", type: "country" },
  { label: "Singapore", code: "65", iso: "SG", type: "country" },
  { label: "Sint Maarten", code: "1-721", iso: "SX", type: "country" },
  { label: "Slovakia", code: "421", iso: "SK", type: "country" },
  { label: "Slovenia", code: "386", iso: "SI", type: "country" },
  { label: "Solomon Islands", code: "677", iso: "SB", type: "country" },
  { label: "Somalia", code: "252", iso: "SO", type: "country" },
  { label: "South Africa", code: "27", iso: "ZA", type: "country" },
  { label: "South Korea", code: "82", iso: "KR", type: "country" },
  { label: "South Sudan", code: "211", iso: "SS", type: "country" },
  { label: "Spain", code: "34", iso: "ES", type: "country" },
  { label: "Sri Lanka", code: "94", iso: "LK", type: "country" },
  { label: "Sudan", code: "249", iso: "SD", type: "country" },
  { label: "Suriname", code: "597", iso: "SR", type: "country" },
  { label: "Svalbard and Jan Mayen", code: "47", iso: "SJ", type: "country" },
  { label: "Swaziland", code: "268", iso: "SZ", type: "country" },
  { label: "Sweden", code: "46", iso: "SE", type: "country" },
  { label: "Switzerland", code: "41", iso: "CH", type: "country" },
  { label: "Syria", code: "963", iso: "SY", type: "country" },
  { label: "Taiwan", code: "886", iso: "TW", type: "country" },
  { label: "Tajikistan", code: "992", iso: "TJ", type: "country" },
  { label: "Tanzania", code: "255", iso: "TZ", type: "country" },
  { label: "Thailand", code: "66", iso: "TH", type: "country" },
  { label: "Togo", code: "228", iso: "TG", type: "country" },
  { label: "Tokelau", code: "690", iso: "TK", type: "country" },
  { label: "Tonga", code: "676", iso: "TO", type: "country" },
  { label: "Trinidad and Tobago", code: "1-868", iso: "TT", type: "country" },
  { label: "Tunisia", code: "216", iso: "TN", type: "country" },
  { label: "Turkey", code: "90", iso: "TR", type: "country" },
  { label: "Turkmenistan", code: "993", iso: "TM", type: "country" },
  {
    label: "Turks and Caicos Islands",
    code: "1-649",
    iso: "TC",
    type: "country",
  },
  { label: "Tuvalu", code: "688", iso: "TV", type: "country" },
  { label: "Uganda", code: "256", iso: "UG", type: "country" },
  { label: "Ukraine", code: "380", iso: "UA", type: "country" },
  { label: "United Arab Emirates", code: "971", iso: "AE", type: "country" },
  { label: "United Kingdom", code: "44", iso: "GB", type: "country" },
  { label: "United States", code: "1", iso: "US", type: "country" },
  { label: "Uruguay", code: "598", iso: "UY", type: "country" },
  { label: "U.S. Virgin Islands", code: "1-340", iso: "VI", type: "country" },
  { label: "Uzbekistan", code: "998", iso: "UZ", type: "country" },
  { label: "Vanuatu", code: "678", iso: "VU", type: "country" },
  { label: "Vatican", code: "379", iso: "VA", type: "country" },
  { label: "Venezuela", code: "58", iso: "VE", type: "country" },
  { label: "Vietnam", code: "84", iso: "VN", type: "country" },
  { label: "Wallis and Futuna", code: "681", iso: "WF", type: "country" },
  { label: "Western Sahara", code: "212", iso: "EH", type: "country" },
  { label: "Yemen", code: "967", iso: "YE", type: "country" },
  { label: "Zambia", code: "260", iso: "ZM", type: "country" },
  { label: "Zimbabwe", code: "263", iso: "ZW", type: "country" },
  { label: "Custom Entry", code: "", iso: "", type: "custom" },
];

export const ownerDetails = {
  userType: "Individual",
  name: "Rashid Khan",
  phoneNumber: "9114367234",
  emailAddress: "Rashid1456@gmail.com",
  status: "Active",
  city: "Bangalore",
  address: "Electronic City 1",
  country: "India",
  postalCode: "562001",
  adhaarCard: "7389 0193 0311",
  dob: "30/12/1994",
  gender: "Male",
  file: ["https://www.google.com", "http://www.facebook.com"],
};

export const tenantDetail = {
  userType: "Individual",
  name: "Rashid Khan",
  phoneNumber: "9114367234",
  emailAddress: "Rashid1456@gmail.com",
  status: "Active",
  city: "Bangalore",
  address: "Electronic City 1",
  country: "India",
  postalCode: "562001",
  adhaarCard: "7389 0193 0311",
  dob: "30/12/1994",
  gender: "Male",
  file: ["https://www.google.com", "http://www.facebook.com"],
};

export const tenantsListing = [
  {
    Id: "1",
    "Tennant Name": "John Smith",

    Property: "123 Main St",
    Unit: "Apt 101",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "2",
    "Tennant Name": "Jane Doe",

    Property: "456 Elm St",
    Unit: "Unit B",
    Status: "Active",
    "KYC Verified": "No",
  },
  {
    Id: "3",
    "Tennant Name": "Michael Johnson",

    Property: "789 Oak Ave",
    Unit: "Suite 201",
    Status: "Inactive",
    "KYC Verified": "Yes",
  },
  {
    Id: "4",
    "Tennant Name": "Emily Brown",
    Property: "321 Pine Rd",
    Unit: "Unit 5",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "5",
    "Tennant Name": "David Wilson",
    Property: "555 Cedar Ln",
    Unit: "Apt 3C",
    Status: "Inactive",
    "KYC Verified": "No",
  },
  {
    Id: "6",
    "Tennant Name": "Sarah Martinez",
    Property: "888 Maple Blvd",
    Unit: "Unit 10",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "7",
    "Tennant Name": "Chris Taylor",
    Property: "999 Spruce Ct",
    Unit: "Apt 202",
    Status: "Inactive",
    "KYC Verified": "No",
  },
  {
    Id: "8",
    "Tennant Name": "Jessica Garcia",
    Property: "777 Birch Ave",
    Unit: "Suite 15",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "9",
    "Tennant Name": "James Rodriguez",
    Property: "222 Pine Rd",
    Unit: "Unit 7",
    Status: "Inactive",
    "KYC Verified": "No",
  },
  {
    Id: "10",
    "Tennant Name": "Emma Thomas",
    Property: "111 Elm St",
    Unit: "Apt 505",
    Status: "Active",
    "KYC Verified": "Yes",
  },
];

export const blocklisting = [
  {
    Id: "1",
    "Block Name": "A",

    Unit: "10",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "2",
    "Block Name": "B",

    Unit: "20",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  {
    Id: "3",
    "Block Name": "C",

    Unit: "30",
    Status: "Active",
    "KYC Verified": "Yes",
  },
  
]

export const leaseListing = [
  {
    // Sn: 1,
    "Lease ID": "L1001",
    "Property Name": "Prestige Towers",
    "Unit No": "A-101",
    "Tenant Name": "Rajesh Kumar",
    "Contract Start Date": "2024-01-01",
    "Contract End Date": "2025-01-01",
    "Payment Type": "Monthly",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 2,
    "Lease ID": "L1002",
    "Property Name": "DLF Heights",
    "Unit No": "B-202",
    "Tenant Name": "Anita Sharma",
    "Contract Start Date": "2024-02-01",
    "Contract End Date": "2025-02-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Under Notice",
  },
  {
    // Sn: 3,
    "Lease ID": "L1003",
    "Property Name": "Brigade Gateway",
    "Unit No": "C-303",
    "Tenant Name": "Vikram Singh",
    "Contract Start Date": "2024-03-01",
    "Contract End Date": "2025-03-01",
    "Payment Type": "Annually",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 4,
    "Lease ID": "L1004",
    "Property Name": "Sobha City",
    "Unit No": "D-404",
    "Tenant Name": "Meena Gupta",
    "Contract Start Date": "2024-04-01",
    "Contract End Date": "2025-04-01",
    "Payment Type": "Monthly",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 5,
    "Lease ID": "L1005",
    "Property Name": "Godrej Infinity",
    "Unit No": "E-505",
    "Tenant Name": "Rohit Jain",
    "Contract Start Date": "2024-05-01",
    "Contract End Date": "2025-05-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 6,
    "Lease ID": "L1006",
    "Property Name": "Purva Skywood",
    "Unit No": "F-606",
    "Tenant Name": "Sneha Reddy",
    "Contract Start Date": "2024-06-01",
    "Contract End Date": "2025-06-01",
    "Payment Type": "Annually",
    "Status Tracking": "Under Notice",
  },
  {
    // Sn: 7,
    "Lease ID": "L1007",
    "Property Name": "Oberoi Splendor",
    "Unit No": "G-707",
    "Tenant Name": "Aditya Verma",
    "Contract Start Date": "2024-07-01",
    "Contract End Date": "2025-07-01",
    "Payment Type": "Monthly",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 8,
    "Lease ID": "L1008",
    "Property Name": "Lodha Bellissimo",
    "Unit No": "H-808",
    "Tenant Name": "Priya Singh",
    "Contract Start Date": "2024-08-01",
    "Contract End Date": "2025-08-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 9,
    "Lease ID": "L1009",
    "Property Name": "Embassy Lake Terraces",
    "Unit No": "I-909",
    "Tenant Name": "Karthik Nair",
    "Contract Start Date": "2024-09-01",
    "Contract End Date": "2025-09-01",
    "Payment Type": "Annually",
    "Status Tracking": "In progress",
  },
  {
    // Sn: 10,
    "Lease ID": "L1010",
    "Property Name": "Raheja Exotica",
    "Unit No": "J-1010",
    "Tenant Name": "Ayesha Khan",
    "Contract Start Date": "2024-10-01",
    "Contract End Date": "2025-10-01",
    "Payment Type": "Monthly",
    "Status Tracking": "Under Notice",
  },
];
export const leaseListingExipred = [
  {
    // Sn: 11,
    "Lease ID": "L1011",
    "Property Name": "Salarpuria Sattva",
    "Unit No": "K-1111",
    "Tenant Name": "Manish Patel",
    "Contract Start Date": "2024-11-01",
    "Contract End Date": "2025-11-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Reject",
  },
  {
    // Sn: 12,
    "Lease ID": "L1012",
    "Property Name": "Hiranandani Gardens",
    "Unit No": "L-1212",
    "Tenant Name": "Neha Malhotra",
    "Contract Start Date": "2024-12-01",
    "Contract End Date": "2025-12-01",
    "Payment Type": "Annually",
    "Status Tracking": "Reject",
  },
  {
    // Sn: 13,
    "Lease ID": "L1013",
    "Property Name": "Prestige Shantiniketan",
    "Unit No": "M-1313",
    "Tenant Name": "Amit Desai",
    "Contract Start Date": "2025-01-01",
    "Contract End Date": "2026-01-01",
    "Payment Type": "Monthly",
    "Status Tracking": "Expired",
  },
  {
    // Sn: 14,
    "Lease ID": "L1014",
    "Property Name": "Kalpataru Horizon",
    "Unit No": "N-1414",
    "Tenant Name": "Pooja Iyer",
    "Contract Start Date": "2025-02-01",
    "Contract End Date": "2026-02-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Expired",
  },
  {
    // Sn: 15,
    "Lease ID": "L1015",
    "Property Name": "ATS Greens Village",
    "Unit No": "O-1515",
    "Tenant Name": "Sanjay Rathore",
    "Contract Start Date": "2025-03-01",
    "Contract End Date": "2026-03-01",
    "Payment Type": "Annually",
    "Status Tracking": "Expired",
  },
  {
    // Sn: 16,
    "Lease ID": "L1016",
    "Property Name": "Mahindra Lifespaces",
    "Unit No": "P-1616",
    "Tenant Name": "Ruchi Thakur",
    "Contract Start Date": "2025-04-01",
    "Contract End Date": "2026-04-01",
    "Payment Type": "Monthly",
    "Status Tracking": "Expired",
  },
  {
    // Sn: 17,
    "Lease ID": "L1017",
    "Property Name": "Tata Housing",
    "Unit No": "Q-1717",
    "Tenant Name": "Sunil Mehta",
    "Contract Start Date": "2025-05-01",
    "Contract End Date": "2026-05-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Expired",
  },
  {
    // Sn: 18,
    "Lease ID": "L1018",
    "Property Name": "Brigade Orchards",
    "Unit No": "R-1818",
    "Tenant Name": "Divya Kapoor",
    "Contract Start Date": "2025-06-01",
    "Contract End Date": "2026-06-01",
    "Payment Type": "Annually",
    "Status Tracking": "Expired",
  },
];
export const leaseListingupcoming = [
  {
    // Sn: 11,
    "Lease ID": "L1011",
    "Property Name": "Salarpuria Sattva",
    "Unit No": "K-1111",
    "Tenant Name": "Manish Patel",
    "Contract Start Date": "2024-11-01",
    "Contract End Date": "2025-11-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Under-Review",
  },
  {
    // Sn: 12,
    "Lease ID": "L1012",
    "Property Name": "Hiranandani Gardens",
    "Unit No": "L-1212",
    "Tenant Name": "Neha Malhotra",
    "Contract Start Date": "2024-12-01",
    "Contract End Date": "2025-12-01",
    "Payment Type": "Annually",
    "Status Tracking": "Under-Review",
  },
  {
    // Sn: 13,
    "Lease ID": "L1013",
    "Property Name": "Prestige Shantiniketan",
    "Unit No": "M-1313",
    "Tenant Name": "Amit Desai",
    "Contract Start Date": "2025-01-01",
    "Contract End Date": "2026-01-01",
    "Payment Type": "Monthly",
    "Status Tracking": "Under-Review",
  },
  {
    // Sn: 14,
    "Lease ID": "L1014",
    "Property Name": "Kalpataru Horizon",
    "Unit No": "N-1414",
    "Tenant Name": "Pooja Iyer",
    "Contract Start Date": "2025-02-01",
    "Contract End Date": "2026-02-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Under-Review",
  },
  {
    // Sn: 15,
    "Lease ID": "L1015",
    "Property Name": "ATS Greens Village",
    "Unit No": "O-1515",
    "Tenant Name": "Sanjay Rathore",
    "Contract Start Date": "2025-03-01",
    "Contract End Date": "2026-03-01",
    "Payment Type": "Annually",
    "Status Tracking": "Modification-Required",
  },
  {
    // Sn: 16,
    "Lease ID": "L1016",
    "Property Name": "Mahindra Lifespaces",
    "Unit No": "P-1616",
    "Tenant Name": "Ruchi Thakur",
    "Contract Start Date": "2025-04-01",
    "Contract End Date": "2026-04-01",
    "Payment Type": "Monthly",
    "Status Tracking": "Modification-Required",
  },
  {
    // Sn: 17,
    "Lease ID": "L1017",
    "Property Name": "Tata Housing",
    "Unit No": "Q-1717",
    "Tenant Name": "Sunil Mehta",
    "Contract Start Date": "2025-05-01",
    "Contract End Date": "2026-05-01",
    "Payment Type": "Quarterly",
    "Status Tracking": "Modification-Required",
  },
  {
    // Sn: 18,
    "Lease ID": "L1018",
    "Property Name": "Brigade Orchards",
    "Unit No": "R-1818",
    "Tenant Name": "Divya Kapoor",
    "Contract Start Date": "2025-06-01",
    "Contract End Date": "2026-06-01",
    "Payment Type": "Annually",
    "Status Tracking": "Modification-Required",
  },
];
export const unitsListing = [
  {
    id: 1,
    unitOrBlock: "A-101",
    property: "Sunset Apartments",
    status: "Occupied",
    bedrooms: 2,
    owner: ["John Doe"],
    tenant: ["Alice Johnson"],
    leaseStatus: "Active",
    contractStartDate: "2023-05-15",
    contractEndDate: "2024-05-14",
    unitType: "Apartment",
    superBuiltUpArea: "1000 sqft",
    terraceArea: "50 sqft",
    plotArea: "1500 sqft",
    exemptFromGST: false,
    unitStatus: "Active",
    unitOccupiedBy: "Alice Johnson",
    duesToBePaidBy: "John Doe",
    availableForSale: true,
    availableForRent: false,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 2,
    numberOfPets: 1,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "5 kW",
    connectedDGLoad: "1 kW",
    complaintType: "None",
    documentCount: 5,
    isHandedOver: true,
  },
  {
    id: 2,
    unitOrBlock: "B-305",
    property: "City View Condos",
    status: "Vacant",
    bedrooms: 1,
    owner: ["Jane Smith"],
    tenant: null,
    leaseStatus: "Not leased",
    contractStartDate: null,
    contractEndDate: null,
    unitType: "Condo",
    superBuiltUpArea: "800 sqft",
    terraceArea: "30 sqft",
    plotArea: "1200 sqft",
    exemptFromGST: true,
    unitStatus: "Available",
    unitOccupiedBy: null,
    duesToBePaidBy: null,
    availableForSale: true,
    availableForRent: true,
    intercom: false,
    tenantType: null,
    societyMembership: "No",
    numberOfWaterInlets: 1,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: true,
    connectedEBLoad: "3 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 2,
    isHandedOver: false,
  },
  {
    id: 3,
    unitOrBlock: "C-201",
    property: "Lakeview Residences",
    status: "Occupied",
    bedrooms: 3,
    owner: ["Michael Johnson"],
    tenant: ["Bob Thompson"],
    leaseStatus: "Active",
    contractStartDate: "2023-08-20",
    contractEndDate: "2024-08-19",
    unitType: "Apartment",
    superBuiltUpArea: "1200 sqft",
    terraceArea: "60 sqft",
    plotArea: "1800 sqft",
    exemptFromGST: false,
    unitStatus: "Active",
    unitOccupiedBy: "Bob Thompson",
    duesToBePaidBy: "Michael Johnson",
    availableForSale: false,
    availableForRent: false,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 3,
    numberOfPets: 2,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "7 kW",
    connectedDGLoad: "2 kW",
    complaintType: "None",
    documentCount: 3,
    isHandedOver: true,
  },
  {
    id: 4,
    unitOrBlock: "C-212",
    property: "Garden Grove",
    status: "Occupied",
    bedrooms: 2,
    owner: ["Sarah Brown"],
    tenant: ["Emily Davis"],
    leaseStatus: "Active",
    contractStartDate: "2022-12-10",
    contractEndDate: "2023-12-09",
    unitType: "Apartment",
    superBuiltUpArea: "950 sqft",
    terraceArea: "40 sqft",
    plotArea: "1400 sqft",
    exemptFromGST: true,
    unitStatus: "Active",
    unitOccupiedBy: "Emily Davis",
    duesToBePaidBy: "Sarah Brown",
    availableForSale: true,
    availableForRent: false,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 2,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: true,
    connectedEBLoad: "4 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 4,
    isHandedOver: true,
  },
  {
    id: 5,
    unitOrBlock: "D-202",
    property: "Downtown Lofts",
    status: "Vacant",
    bedrooms: 1,
    owner: ["David Wilson"],
    tenant: null,
    leaseStatus: "Not leased",
    contractStartDate: null,
    contractEndDate: null,
    unitType: "Loft",
    superBuiltUpArea: "900 sqft",
    terraceArea: "20 sqft",
    plotArea: "1300 sqft",
    exemptFromGST: false,
    unitStatus: "Available",
    unitOccupiedBy: null,
    duesToBePaidBy: null,
    availableForSale: false,
    availableForRent: true,
    intercom: false,
    tenantType: null,
    societyMembership: "No",
    numberOfWaterInlets: 1,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "2 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 1,
    isHandedOver: false,
  },
  {
    id: 6,
    unitOrBlock: "A-202",
    property: "Ocean View Towers",
    status: "Occupied",
    bedrooms: 3,
    owner: ["Jennifer Lee"],
    tenant: ["Mark Taylor"],
    leaseStatus: "Active",
    contractStartDate: "2023-02-28",
    contractEndDate: "2024-02-27",
    unitType: "Apartment",
    superBuiltUpArea: "1100 sqft",
    terraceArea: "45 sqft",
    plotArea: "1600 sqft",
    exemptFromGST: true,
    unitStatus: "Active",
    unitOccupiedBy: "Mark Taylor",
    duesToBePaidBy: "Jennifer Lee",
    availableForSale: false,
    availableForRent: false,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 2,
    numberOfPets: 1,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "6 kW",
    connectedDGLoad: "1 kW",
    complaintType: "None",
    documentCount: 3,
    isHandedOver: true,
  },
  {
    id: 7,
    unitOrBlock: "C-702",
    property: "Hillside Estates",
    status: "Vacant",
    bedrooms: 2,
    owner: ["Robert Miller"],
    tenant: null,
    leaseStatus: "Not leased",
    contractStartDate: null,
    contractEndDate: null,
    unitType: "Apartment",
    superBuiltUpArea: "950 sqft",
    terraceArea: "30 sqft",
    plotArea: "1400 sqft",
    exemptFromGST: false,
    unitStatus: "Available",
    unitOccupiedBy: null,
    duesToBePaidBy: null,
    availableForSale: true,
    availableForRent: true,
    intercom: false,
    tenantType: null,
    societyMembership: "No",
    numberOfWaterInlets: 1,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "3 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 2,
    isHandedOver: false,
  },
  {
    id: 8,
    unitOrBlock: "C-405",
    property: "Riverside Villas",
    status: "Occupied",
    bedrooms: 1,
    owner: ["Carol Wilson"],
    tenant: ["Daniel Clark"],
    leaseStatus: "Active",
    contractStartDate: "2023-09-10",
    contractEndDate: "2024-09-09",
    unitType: "Villa",
    superBuiltUpArea: "700 sqft",
    terraceArea: "10 sqft",
    plotArea: "1000 sqft",
    exemptFromGST: true,
    unitStatus: "Active",
    unitOccupiedBy: "Daniel Clark",
    duesToBePaidBy: "Carol Wilson",
    availableForSale: false,
    availableForRent: true,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 1,
    numberOfPets: 1,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "2 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 3,
    isHandedOver: true,
  },
  {
    id: 9,
    unitOrBlock: "B-402",
    property: "Parkside Gardens",
    status: "Vacant",
    bedrooms: 2,
    owner: ["Lisa Davis"],
    tenant: null,
    leaseStatus: "Not leased",
    contractStartDate: null,
    contractEndDate: null,
    unitType: "Apartment",
    superBuiltUpArea: "950 sqft",
    terraceArea: "20 sqft",
    plotArea: "1300 sqft",
    exemptFromGST: false,
    unitStatus: "Available",
    unitOccupiedBy: null,
    duesToBePaidBy: null,
    availableForSale: true,
    availableForRent: false,
    intercom: false,
    tenantType: null,
    societyMembership: "No",
    numberOfWaterInlets: 1,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: true,
    connectedEBLoad: "2 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 1,
    isHandedOver: false,
  },
  {
    id: 10,
    unitOrBlock: "A-212",
    property: "Mountain View Heights",
    status: "Occupied",
    bedrooms: 3,
    owner: ["Kevin Brown"],
    tenant: ["Sophia Martinez"],
    leaseStatus: "Active",
    contractStartDate: "2023-04-05",
    contractEndDate: "2024-04-04",
    unitType: "Apartment",
    superBuiltUpArea: "1150 sqft",
    terraceArea: "35 sqft",
    plotArea: "1550 sqft",
    exemptFromGST: false,
    unitStatus: "Active",
    unitOccupiedBy: "Sophia Martinez",
    duesToBePaidBy: "Kevin Brown",
    availableForSale: true,
    availableForRent: false,
    intercom: true,
    tenantType: "Individual",
    societyMembership: "Yes",
    numberOfWaterInlets: 2,
    numberOfPets: 0,
    electricityConnection: "Yes",
    waterConnection: "Yes",
    needPaperInvoice: false,
    connectedEBLoad: "6 kW",
    connectedDGLoad: "N/A",
    complaintType: "None",
    documentCount: 2,
    isHandedOver: true,
  },
];

export const leaaseData = [
  {
    "Check No.": "001",
    "PDC Check": "2024-07-01",
    "Unpaid Amt": 5000,
    "Paid Amt": 3000,
    "Partial Paid Amt": 2000,
    "Fit Out Date": "2024-08-01",
    "Move in Date": "2024-08-15",
    "Visitor Pass": "AB123",
    "Property Verified": true,
    Action: "Review",
  },
  {
    "Check No.": "002",
    "PDC Check": "2024-07-02",
    "Unpaid Amt": 6000,
    "Paid Amt": 6000,
    "Partial Paid Amt": 0,
    "Fit Out Date": "2024-08-05",
    "Move in Date": "2024-08-20",
    "Visitor Pass": "CD456",
    "Property Verified": true,
    Action: "Complete",
  },
  {
    "Check No.": "003",
    "PDC Check": "2024-07-03",
    "Unpaid Amt": 4500,
    "Paid Amt": 1000,
    "Partial Paid Amt": 3500,
    "Fit Out Date": "2024-08-10",
    "Move in Date": "2024-08-25",
    "Visitor Pass": "EF789",
    "Property Verified": false,
    Action: "Follow Up",
  },
  {
    "Check No.": "004",
    "PDC Check": "2024-07-04",
    "Unpaid Amt": 7000,
    "Paid Amt": 7000,
    "Partial Paid Amt": 0,
    "Fit Out Date": "2024-08-15",
    "Move in Date": "2024-09-01",
    "Visitor Pass": "GH012",
    "Property Verified": true,
    Action: "Complete",
  },
  {
    "Check No.": "005",
    "PDC Check": "2024-07-05",
    "Unpaid Amt": 8000,
    "Paid Amt": 2000,
    "Partial Paid Amt": 6000,
    "Fit Out Date": "2024-08-20",
    "Move in Date": "2024-09-05",
    "Visitor Pass": "IJ345",
    "Property Verified": false,
    Action: "Pending",
  },
  {
    "Check No.": "006",
    "PDC Check": "2024-07-06",
    "Unpaid Amt": 3000,
    "Paid Amt": 3000,
    "Partial Paid Amt": 0,
    "Fit Out Date": "2024-08-25",
    "Move in Date": "2024-09-10",
    "Visitor Pass": "KL678",
    "Property Verified": true,
    Action: "Complete",
  },
  {
    "Check No.": "007",
    "PDC Check": "2024-07-07",
    "Unpaid Amt": 5500,
    "Paid Amt": 2500,
    "Partial Paid Amt": 3000,
    "Fit Out Date": "2024-08-30",
    "Move in Date": "2024-09-15",
    "Visitor Pass": "MN901",
    "Property Verified": true,
    Action: "Review",
  },
  {
    "Check No.": "008",
    "PDC Check": "2024-07-08",
    "Unpaid Amt": 9000,
    "Paid Amt": 5000,
    "Partial Paid Amt": 4000,
    "Fit Out Date": "2024-09-05",
    "Move in Date": "2024-09-20",
    "Visitor Pass": "OP234",
    "Property Verified": false,
    Action: "Follow Up",
  },
  {
    "Check No.": "009",
    "PDC Check": "2024-07-09",
    "Unpaid Amt": 3500,
    "Paid Amt": 3500,
    "Partial Paid Amt": 0,
    "Fit Out Date": "2024-09-10",
    "Move in Date": "2024-09-25",
    "Visitor Pass": "QR567",
    "Property Verified": true,
    Action: "Complete",
  },
  {
    "Check No.": "010",
    "PDC Check": "2024-07-10",
    "Unpaid Amt": 4000,
    "Paid Amt": 1000,
    "Partial Paid Amt": 3000,
    "Fit Out Date": "2024-09-15",
    "Move in Date": "2024-10-01",
    "Visitor Pass": "ST890",
    "Property Verified": true,
    Action: "Pending",
  },
];

export const leaseDetailData = [];

export const ownerContactCard = [
  {
    ownerType: "Owner",
    ownerName: "John Doe",
    ownerPhone: "(555) 123-4567",
    ownerEmail: "john.doe@example.com",
  },
  {
    ownerType: "Owner",
    ownerName: "Sarah Smith",
    ownerPhone: "(555) 987-6543",
    ownerEmail: "sarah.smith@company.com",
  },
  {
    ownerType: "Tenant",
    ownerName: "Alex Johnson",
    ownerPhone: "(555) 246-8101",
    ownerEmail: "alex.johnson@domain.com",
  },
  {
    ownerType: "Tenant",
    ownerName: "Emma Brown",
    ownerPhone: "(555) 135-7912",
    ownerEmail: "emma.brown@business.org",
  },
];

export const paymentDetail = [
  {
    paymentTerm: "Quarter 1",
    rentAmount: 36000,
  },
  {
    paymentTerm: "Quarter 2",
    rentAmount: 36000,
  },
  {
    paymentTerm: "Quarter 3",
    rentAmount: 36000,
  },
  {
    paymentTerm: "Quarter 4",
    rentAmount: 36000,
  },
];

export const companiesData = [
  {
    id: 1,
    company: "ABC Corp",
    address: "123 Elm Street, Springfield, IL, 62701",
    associatedProperties: ["Property A", "Property B"],
    status: "Active",
  },
  {
    id: 2,
    company: "XYZ Ltd",
    address: "456 Oak Avenue, Metropolis, NY, 10001",
    associatedProperties: ["Property C", "Property D"],
    status: "Inactive",
  },
  {
    id: 3,
    company: "Tech Innovations",
    address: "789 Pine Road, Gotham, NJ, 07001",
    associatedProperties: ["Property E", "Property F"],
    status: "Active",
  },
  {
    id: 4,
    company: "Global Solutions",
    address: "101 Maple Drive, Rivertown, CA, 90210",
    associatedProperties: ["Property G", "Property H"],
    status: "Active",
  },
  {
    id: 5,
    company: "Future Tech",
    address: "202 Birch Lane, Lakeside, FL, 33101",
    associatedProperties: ["Property I", "Property J"],
    status: "Inactive",
  },
  {
    id: 6,
    company: "Creative Enterprises",
    address: "303 Cedar Street, Hilltop, TX, 73301",
    associatedProperties: ["Property K", "Property L"],
    status: "Active",
  },
  {
    id: 7,
    company: "Prime Solutions",
    address: "404 Spruce Avenue, Valleyview, WA, 98001",
    associatedProperties: ["Property M", "Property N"],
    status: "Active",
  },
  {
    id: 8,
    company: "Innovative Designs",
    address: "505 Willow Road, Beachside, OR, 97201",
    associatedProperties: ["Property O", "Property P"],
    status: "Inactive",
  },
  {
    id: 9,
    company: "Vertex Technologies",
    address: "606 Poplar Street, Greenfield, CO, 80001",
    associatedProperties: ["Property Q", "Property R"],
    status: "Active",
  },
  {
    id: 10,
    company: "Dynamic Ventures",
    address: "707 Ash Avenue, Mountainview, UT, 84101",
    associatedProperties: ["Property S", "Property T"],
    status: "Inactive",
  },
];

export const membersListing = [
  {
    block: "Lakeside Horizon",
    unit: "1210",
    relationship: "Co Owner",
    isResiding: true,
    fullName: "John Doe",
    email: "john@doe.com",
    phoneNumber: "987654310",
    gender: "male",
    dob: "24/07/1985",
    aadharNumber: "123129399223",
    panNumber: "ABCDE1234F",
    passportNumber: "ASKHFI89AF",
    passportExpirationDate: "12/07/2030",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1211",
    relationship: "Owner's Family",
    isResiding: false,
    fullName: "Jane Smith",
    email: "jane@smith.com",
    phoneNumber: "987654311",
    gender: "female",
    dob: "15/03/1990",
    aadharNumber: "123456789012",
    panNumber: "XYZAB4567C",
    passportNumber: "BSJDKL92QW",
    passportExpirationDate: "11/11/2027",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1212",
    relationship: "Registered Owner",
    isResiding: true,
    fullName: "Michael Johnson",
    email: "michael@johnson.com",
    phoneNumber: "987654312",
    gender: "male",
    dob: "10/12/1982",
    aadharNumber: "234567890123",
    panNumber: "LMNOP7890Q",
    passportNumber: "DFGJLD83RK",
    passportExpirationDate: "22/04/2025",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1213",
    relationship: "Tenant",
    isResiding: true,
    fullName: "Emily Davis",
    email: "emily@davis.com",
    phoneNumber: "987654313",
    gender: "female",
    dob: "29/06/1988",
    aadharNumber: "345678901234",
    panNumber: "QRSTU1234V",
    passportNumber: "GHJKLM77RT",
    passportExpirationDate: "05/08/2028",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1214",
    relationship: "Tenant's Family",
    isResiding: false,
    fullName: "David Brown",
    email: "david@brown.com",
    phoneNumber: "987654314",
    gender: "male",
    dob: "17/11/1985",
    aadharNumber: "456789012345",
    panNumber: "UVWXZ5678Y",
    passportNumber: "JKLNBV90FG",
    passportExpirationDate: "19/01/2026",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1215",
    relationship: "Co Owner",
    isResiding: true,
    fullName: "Sarah Wilson",
    email: "sarah@wilson.com",
    phoneNumber: "987654315",
    gender: "female",
    dob: "03/04/1992",
    aadharNumber: "567890123456",
    panNumber: "IJKL5678M",
    passportNumber: "LMNOPQ56TY",
    passportExpirationDate: "23/06/2029",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1216",
    relationship: "Owner's Family",
    isResiding: true,
    fullName: "Daniel Lee",
    email: "daniel@lee.com",
    phoneNumber: "987654316",
    gender: "male",
    dob: "21/09/1979",
    aadharNumber: "678901234567",
    panNumber: "MNOP3456R",
    passportNumber: "ZXCVBN34DF",
    passportExpirationDate: "30/12/2025",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1217",
    relationship: "Registered Owner",
    isResiding: false,
    fullName: "Olivia Martin",
    email: "olivia@martin.com",
    phoneNumber: "987654317",
    gender: "female",
    dob: "12/02/1980",
    aadharNumber: "789012345678",
    panNumber: "ABCD7890E",
    passportNumber: "QWERTY12RT",
    passportExpirationDate: "17/07/2026",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1219",
    relationship: "Tenant's Family",
    isResiding: true,
    fullName: "Sophia Garcia",
    email: "sophia@garcia.com",
    phoneNumber: "987654319",
    gender: "female",
    dob: "08/05/1987",
    aadharNumber: "901234567890",
    panNumber: "IJKL8901M",
    passportNumber: "BVCXDF45TY",
    passportExpirationDate: "13/11/2027",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1220",
    relationship: "Co Owner",
    isResiding: false,
    fullName: "Ethan Clark",
    email: "ethan@clark.com",
    phoneNumber: "987654320",
    gender: "male",
    dob: "22/01/1993",
    aadharNumber: "012345678901",
    panNumber: "MNOP8901Q",
    passportNumber: "CVBNM34OP",
    passportExpirationDate: "25/05/2028",
    property: "Sunset Villa",
  },
  {
    block: "Lakeside Horizon",
    unit: "1221",
    relationship: "Registered Owner",
    isResiding: true,
    fullName: "Mia Adams",
    email: "mia@adams.com",
    phoneNumber: "987654321",
    gender: "female",
    dob: "30/07/1984",
    aadharNumber: "123456789012",
    panNumber: "QRSTU1234R",
    passportNumber: "QWERTY76IK",
    passportExpirationDate: "01/09/2031",
    property: "Sunset Villa",
  },
];
